[Icon Theme]
Name=elementary
Comment=Smooth modern theme designed to be intuitive.
Inherits=elementary,gnome,ubuntu-mono-light,hicolor,gnome-colors-brave

Example=directory-x-normal

#Directory list
Directories=panel/16,panel/22,panel/24,panel/48,

[panel/16]
Size=16
Context=Status
Type=Fixed

[panel/22]
Size=22
Context=Status
Type=Fixed

[panel/24]
Size=24
Context=Status
Type=Fixed

[panel/48]
Size=48
Context=Status
Type=Scalable
