#!/bin/sh

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    update-alternatives --remove x-cursor-theme /usr/share/icons/elementary/cursor.theme
fi

rm -f /usr/share/icons/elementary/icon-theme.cache

#DEBHELPER#
