name: Gettext Updates

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/elementary/docker:next-unstable

    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install git -y

    - name: Clone repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Update Translation Files
      uses: elementary/actions/gettext-template@next
      env:
        GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
